# Generated by Django 5.0.7 on 2024-08-05 10:08

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[user.models.validate_mobile_number])),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('Address', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
