# Generated by Django 5.0.7 on 2024-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address_user_address_remove_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='college',
            new_name='clgName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='1.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], default='Student', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
