# Generated by Django 5.0.7 on 2024-08-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_company_id_alter_company_name'),
        ('user', '0006_remove_user_id_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.company'),
        ),
    ]
