# Generated by Django 5.0.7 on 2024-08-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cmpName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cmpUrl',
        ),
    ]
