# Generated by Django 5.0.7 on 2024-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
