# Generated by Django 5.0.7 on 2024-08-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_category_delete_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='1.img', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
