# Generated by Django 5.0.7 on 2024-08-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_company_email_job_logo_job_salary_from_job_salary_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
