# Generated by Django 5.0.7 on 2024-08-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_company_id_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.company'),
            preserve_default=False,
        ),
    ]
